import "../styles/globals.css";
import "antd/dist/antd.css";
import Head from "next/head";
import CustomLayout from "../components/CustomLayout";
import useTranslation from "next-translate/useTranslation";

function MyApp({ Component, pageProps }) {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomLayout>
        <Component {...pageProps} />
      </CustomLayout>
    </>
  );
}

export default MyApp;
